apiVersion: v1
kind: Service
metadata: 
  name: cache-service
  labels:
    app: crimereport
spec:
  type: ClusterIP
  ports: 
  - name: tcp
    protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: crimereport
