apiVersion: v1
kind: Service
metadata: 
  name: database-service
  labels:
    app: crimereport
spec:
  type: ClusterIP
  ports: 
  - name: tcp
    protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: crimereport
