apiVersion: v1
kind: Service
metadata: 
  name: eureka-service
  labels:
    app: crimereport
spec:
  type: ClusterIP
  ports: 
  - name: tcp
    protocol: TCP
    port: 8761
    targetPort: 8761
  selector:
    app: crimereport
