apiVersion: v1
kind: Service
metadata: 
  name: gateway-service
  labels:
    app: crimereport
spec:
  type: ClusterIP
  ports: 
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: crimereport