apiVersion: v1
kind: Service
metadata: 
  name: load-balancer
  labels:
    app: crimereport
  annotations: 
    kubernetes.io/elb.keepalive_timeout: '10'
spec:
  type: LoadBalancer
  ports:
  - name: eureka-gateway
    port: 8761
    targetPort: 8761
  - name: rabbit-mgmt
    port: 15672
    targetPort: 15672
  - name: rabbit-gateway
    port: 5672
    targetPort: 5672
  - name: cache-gateway
    port: 5000
    targetPort: 5000
  - name: database-gateway
    port: 8000
    targetPort: 8000
  - name: gateway
    port: 3000
    targetPort: 3000  
  selector:
    app: crimereport
