apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-deployment
  labels:
    app: crimereport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crimereport
  template:
    metadata:
      labels:
        app: crimereport
    spec:
      containers:
      - name: logger
        image: 924809052459.dkr.ecr.us-east-1.amazonaws.com/logger:v1
        imagePullPolicy: IfNotPresent
