apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-deployment
  labels:
    app: crimereport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crimereport
  template:
    metadata:
      labels:
        app: crimereport
    spec:
      containers:
      - name: rabbit
        image: 924809052459.dkr.ecr.us-east-1.amazonaws.com/rabbit:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5672
        - containerPort: 15672
        