apiVersion: v1
kind: Service
metadata: 
  name: rabbit-service
  labels:
    app: crimereport
spec:
  type: ClusterIP
  ports: 
  - name: tcp
    protocol: TCP
    port: 5672
    targetPort: 5672
  selector:
    app: crimereport